# Global project configuration
project:
  name: "Lumbar Spine Degenerative Classification"
  description: "Automated evaluation of degenerative lumbar spine changes from MRI images using deep learning."
  seed: 42

# Kaggle API config
kaggle:
  competition: "rsna-2024-lumbar-spine-degenerative-classification"
  download_path: "./data"

# Data configuration
data:
  raw_path: "./data/raw"
  interim_path: "./data/interim/"
  processed_path: "./data/processed"

# Preprocessing parameters
preprocessing:
  target_disc: "L4/L5"
  final_depth: 1
  final_size: [96, 96]
  cropped_size: [512, 512]
  cropping:
    scs:
      sagt2:
        left: 96
        right: 32
        upper: 40
        lower: 40
    nfn:
      sagt1:
        left: 96
        right: 32
        upper: 40
        lower: 40
  mode: "target_window" # or "full_series"
  target_window:
    slices_before: 1
    slices_after: 1


# Model / Training configuration
training:
  # Possible values (4 modes):
  #  - single_multiclass
  #  - single_binary
  #  - multi_multiclass
  #  - multi_binary
  classification_mode: "multi_multiclass"  
  
  # Disease used for single-disease modes
  disease: "lnfn"

  # Name of the folder in data/interim containing .pt files
  selected_tensor_folder: "target_window_128x128_5D_B2A2"

  # Model architecture: "simple_3dcnn", "advanced_single", "advanced_single_improved", "advanced_multi", "resnet3d"
  model_arch: "resnet3d"
  
  # Splitting
  test_size: 0.2
  validation_split_of_temp: 0.5

  # Hyperparams
  batch_size: 32
  num_epochs: 50
  learning_rate: 0.001
  dropout_prob: 0.3
  
  # Early stopping
  early_stopping_patience: 50

  excluded_studies:
    - 2780132468
    - 2492114990